- .github/.goreleaser.yml
- .github/workflows/release.yml
Update goreleaser settings and release job for a release to contain OS-specific archives and checksums
> feat: update release job

- README.md
- t.md
- todo
> docs: initial rework of README.md

- .goreleaser.yml
- README.md
Add nfpms packages into release.
Add homebrew formula update after a successful release.
Resolves https://github.com/tofuutils/tenv/issues/14, https://github.com/tofuutils/tenv/issues/33
> feat: add nfpms packages and homebrew to release

- README.md
Add documentation on how to use .terraform-version.
Keep format and wording from .opentofu-version for clarity
> Add support for .terraform-version file

- .goreleaser.yml
> feat: add Chocolatey package

- README.md
- config/config.go
- versionmanager/builder/builder.go
- versionmanager/manager.go
- versionmanager/semantic/walker.go
> Merge feat/env-var-fallback

- README.md
- config/remote.go
- go.sum
- versionmanager/retriever/html/htmlretriever.go
- versionmanager/retriever/terraform/terraformretriever.go
- versionmanager/retriever/terragrunt/terragruntretriever.go
- versionmanager/retriever/tofu/tofuretriever.go
> Merge feat/detect-artifactory

- versionmanager/proxy/proxy.go
> bugfix: proxy transmit increasing signal

- README.md
- cmd/tenv/tenv.go
- config/config.go
- versionmanager/proxy/proxy.go
> Add update-path command

- versionmanager/proxy/proxy.go
> Restore normal display when exposing outputs to GitHub Actions

- README.md
Follows on from #46 to tidy up trivial formatting of spaces and extraneous characters.
Proposed tweaks been tested/[validated here](https://github.com/DevSecTop/TF-via-PR-Comments/pull/193/files).
> docs: trivial formatting of installation steps

- README.md
- cmd/tenv/subcmd.go
- versionmanager/semantic/semantic.go
> Add regexp constraint support

- .github/workflows/choco.yml
> Add automatic chocolatey release

- go.mod
- go.sum
- pkg/lockfile/lockfile.go
- versionmanager/manager.go
> Write a lock file during install

- README.md
added documentation for atmos integration
> docs: updated README to include atmos

- go.sum
- pkg/lockfile/lockfile.go
- versionmanager/manager.go
Avoid potential conflicting behavior between pkg/lockfile.CleanAndExitOnInterrupt and  versionmanager/proxy.transmitIncreasingSignal
> Improve interrupt signal handling

- pkg/lockfile/lockfile.go
> bugfix: proper lock file close

- CODE_OF_CONDUCT.md
- README.md
- config/remote.go
- go.mod
- go.sum
> Change default proxy behavior

- README.md
README updated: add info about installation via Nix
> docs: add info about installation via Nix

- config/config.go
- go.sum
- pkg/check/cosign/check.go
- pkg/check/cosign/check_test.go
- pkg/lockfile/lockfile_test.go
- pkg/loghelper/loghelper.go
- versionmanager/retriever/tofu/tofuretriever.go
> log cosign outputs

- pkg/apimsg/apimsg.go
- versionmanager/retriever/atmos/atmosretriever.go
- versionmanager/retriever/terraform/terraformretriever.go
- versionmanager/retriever/terragrunt/terragruntretriever.go
- versionmanager/retriever/tofu/tofuretriever.go
> Log searched assets

- versionmanager/retriever/terragrunt/terragruntretriever.go
https://github.com/tofuutils/tenv/issues/162
> fix: terragrunt installation on Windows

- versionmanager/retriever/terragrunt/terragruntretriever.go
> fix: terragrunt binary name

- .goreleaser.yml
> feat: add AUR publish to goreleaser

- go.mod
> fix: set v2 in go.mod

- cmd/tenv/subcmd.go
- cmd/tenv/tenv.go
- versionmanager/manager.go
Several improvement following #165 and #185
> Fix use cmd when auto install is disabled

- cmd/tenv/subcmd.go
- versionmanager/manager.go
- versionmanager/proxy/light/light.go
> Fixes: light proxy did not pipe stdin, detect command empty display on error 

- README.md
- cmd/tenv/tenv.go
- versionmanager/builder/builder.go
- versionmanager/manager.go
- versionmanager/proxy/agnostic.go
- versionmanager/proxy/proxy.go
- versionmanager/semantic/parser/flat/flatparser.go
- versionmanager/semantic/parser/iac/iacparser.go
- versionmanager/semantic/parser/terragrunt/gruntparser.go
- versionmanager/semantic/semantic.go
- versionmanager/semantic/types/types.go
> Add .tofu files support

- versionmanager/manager.go
> Double check on installed version

- README.md
- cmd/tenv/subcmd.go
- config/config.go
> Add install flag

- cmd/tenv/subcmd.go
- go.mod
- go.sum
> display last use in list

- cmd/tenv/subcmd.go
- config/config.go
- go.mod
- go.sum
- versionmanager/retriever/terraform/terraformretriever.go
- versionmanager/retriever/tofu/tofuretriever.go
> add skip-signature flag

- versionmanager/retriever/tofu/tofuretriever.go
> fix cosign check in tofu install

- pkg/cmdproxy/proxy.go
- versionmanager/proxy/light/light.go
> Fix: proxy exit code with github action

- README.md
As discussed on #212 - an update to the docs to help others if wanting to verify signatures of `tenv` releases.
I went into more detail to also cover a use case if anyone is wanting to automate the installation in a developer environment. Where `tenv` cannot be natively installed via a package manager.
Hope all is okay!
closes #215
> docs: add guidance around tenv sig verification

- README.md
- cmd/tenv/tenv.go
- cmd/tenv/textui.go
- go.mod
- go.sum
- versionmanager/manager.go
> Add interactive mode (call without subcommand)

- README.md
- cmd/tenv/tenv.go
- cmd/tenv/textui.go
- config/config.go
- config/remote.go
- versionmanager/builder/builder.go
- versionmanager/proxy/agnostic.go
- versionmanager/retriever/api/api.go
- versionmanager/retriever/terraform/terraformretriever.go
- versionmanager/retriever/tofu/dl/tofudl.go
- versionmanager/retriever/tofu/tofuretriever.go
> Add TofuDL mirroring format support

- pkg/check/cosign/check_test.go
> fix : skip all cosign tests

- versionmanager/semantic/parser/iac/iacparser.go
> Fix : read iac files from WorkPath (chdir proxy flag)

- cmd/tenv/subcmd.go
We have a use case where we pre-install terraform and terragrunt versions for pipeline usage, to ensure we don't get rate limited. The problem is, that if the installation fails, it does not fail the build process. This is because tenv always exists with status `0`.
You can simulate this with 
```shell
tenv tf install v5000
Installing Terraform 5000.0.0
Fetching release information from https://releases.hashicorp.com/terraform/5000.0.0/index.json
unexpected value returned by API
echo $?
0
```
This change makes use of Cobra's `RunE` command instead of just the `Run` command for all sub command calls. This will allow any error event in the run command to cause tenv to exit with a non zero value. This is useful to detect install and update failures in scripts.
Sample output with the change …
> Update Cobra sub commands to use RunE

- cmd/tenv/subcmd.go
- cmd/tenv/tenv.go
- cmd/tenv/textui.go
- go.mod
- go.sum
> Avoid duplicate error message display 

- README.md
> docs: add Oh My Zsh completion

- .github/workflows/release.yml
> update go version in release.yml

- versionmanager/proxy/detached_others.go
- versionmanager/proxy/detached_windows.go
- versionmanager/proxy/proxy.go
> Fix : specialize build to avoid missing pgid error on windows

- versionmanager/proxy/agnostic.go
- versionmanager/proxy/detach/detached_others.go
- versionmanager/proxy/detach/detached_windows.go
- versionmanager/proxy/light/light.go
- versionmanager/proxy/proxy.go
> use TENV_DETACHED_PROXY in lightproxy

- .github/workflows/create-new-release-tag.yml
> feat: add new GH action

- README.md
- versionmanager/builder/builder.go
- versionmanager/semantic/parser/asdf/asdf.go
https://github.com/tofuutils/tenv/issues/301#issuecomment-2558158736
> feat: add support of .tool-versions

- README.md
- versionmanager/proxy/detach/detached_others.go
> Change default for TENV_DETACHED_PROXY on non windows OS #255

- README.md
- config/config.go
- versionmanager/proxy/detach/detached_others.go
- versionmanager/proxy/detach/detached_windows.go
> Feat: CI or PIPELINE_WORKSPACE change default detached proxy behavior instead of ignoring TENV_DETACHED_PROXY

- .goreleaser.yml
> feat(goreleaser): enable release discussions and prerelease support

- .goreleaser.yml
> feat(goreleaser): add slack/telegram announces

- .goreleaser.yml
> feat(goreleaser): add DMG support

- .github/workflows/release.yml
> feat(goreleaser): switch to goreleaser-pro

- .github/workflows/release.yml
- .goreleaser.yml
> Add cloudsmith support

- .github/workflows/release.yml
> fix: goreleaser pro installation

- cmd/tenv/tenv.go
- config/config.go
- config/envname/env.go
- config/utils/utils.go
- go.mod
- go.sum
- pkg/cmdproxy/proxy.go
- pkg/tty/tty.go
- versionmanager/builder/builder.go
- versionmanager/prefix.go
- versionmanager/proxy/agnostic.go
- versionmanager/proxy/detach/detached_others.go
- versionmanager/proxy/detach/detached_windows.go
- versionmanager/proxy/light/custom_env_others.go
- versionmanager/proxy/light/custom_env_windows.go
- versionmanager/proxy/light/light.go
- versionmanager/proxy/proxy.go
- versionmanager/retriever/atmos/atmosretriever.go
- versionmanager/retriever/terraform/terraformretriever.go
- versionmanager/retriever/terragrunt/terragruntretriever.go
- versionmanager/retriever/tofu/tofuretriever.go
> detect TTY mode on non windows OS to change TENV_DETACHED_PROXY default

- README.md
- cmd/tenv/tenv.go
- config/envname/env.go
> Switch tofu and terraform proxies to agnostic proxies with env var

- Makefile
- test/e2e/e2e_test.go
Add a couple of basic tests that can be run by:
`make e2e_test`
> Add basic end to end tests

- README.md
- config/envname/env.go
- pkg/check/cosign/check.go
- pkg/cmdproxy/proxy.go
- pkg/fileperm/permissions.go
- pkg/lockfile/lockfile.go
- pkg/lockfile/lockfile_test.go
- pkg/zip/zip.go
- versionmanager/lastuse/last.go
- versionmanager/manager.go
- versionmanager/proxy/agnostic.go
- versionmanager/proxy/proxy.go
- versionmanager/semantic/uninstall.go
- versionmanager/tenvlib/lib.go
> Add TENV_SKIP_LAST_USE and improve file permissions consistency

- test/e2e/e2e_test.go
Added several new tests and descriptions for all the others.
> Add end-to-end tests for the latest features

- README.md
test GitHub page looks good https://nmishin.github.io/tenv/
> Fix Readme syntax for Jekyll compatibility

- .goreleaser.yml
- README.md
- cmd/tenv/subcmd.go
- cmd/tenv/tenv.go
- cmd/tenv/textui.go
- cmd/terramate/terramate.go
- config/cmdconst/constant.go
- config/config.go
- config/envname/env.go
- config/remote.go
- go.mod
- go.sum
- pkg/archname/arch.go
- pkg/loghelper/loghelper.go
- pkg/uncompress/sanitize/sanitize.go
- pkg/uncompress/sanitize/sanitize_test.go
- pkg/uncompress/targz/targz.go
- pkg/uncompress/uncompress.go
- pkg/uncompress/zip/zip.go
- versionmanager/builder/builder.go
- versionmanager/retriever/terraform/terraformretriever.go
- versionmanager/retriever/terramate/terramateretriever.go
- versionmanager/retriever/tofu/tofuretriever.go
- versionmanager/semantic/parser/asdf/asdfparser.go
- versionmanager/tenvlib/examples/dtofuver/ex1.go
- versionmanager/tenvlib/examples/ltfver/ex2.go
> add terramate support

- cmd/tenv/subcmd.go
> -k flag default come from env var

- go.mod
- go.sum
- versionmanager/manager.go
- versionmanager/retriever/terragrunt/terragruntretriever.go
- versionmanager/semantic/finder/finder.go
- versionmanager/semantic/finder/finder_test.go
> Fix : handle terragrunt alpha version format

- .goreleaser_release_only.yml
This reverts commit b66c29e25b2f54f949130fc6c201c5efb86369b6.
Revert for now.
> Revert "Simplify goreleaser config for cloudsmith repos"

- versionmanager/manager.go
- versionmanager/semantic/finder/finder.go
- versionmanager/semantic/finder/finder_test.go
> Fix versionfinder match against version constraint

- README.md
- cmd/tenv/tenv.go
- config/config.go
- config/utils/utils.go
- pkg/download/pgpkey.go
- pkg/download/pgpkey_test.go
- pkg/lockfile/lockfile_test.go
- versionmanager/retriever/terraform/terraformretriever.go
- versionmanager/retriever/terraform/url/terraformurl.go
- versionmanager/retriever/tofu/tofuretriever.go
- versionmanager/retriever/tofu/url/tofuurl.go
closes https://github.com/tofuutils/tenv/issues/400
> feat: add URL support to HASHICORP_PGP_KEY

- .goreleaser_release_only.yml
Fix for https://github.com/tofuutils/tenv/issues/437
> Feat: Rework package loading into Cloudsmith
